project 'tentenbox.xcodeproj'
platform :ios, '10.0'

target 'tentenbox' do
  use_frameworks!
  
  # code rules
  # https://github.com/realm/SwiftLint
  pod 'SwiftLint'

  # icons
  # https://github.com/PrideChung/FontAwesomeKit
  pod 'FontAwesomeKit/FontAwesome'

  # colors
  # https://github.com/viccalexander/Chameleon/issues/208
  pod 'ChameleonFramework/Swift', :git => 'https://github.com/ViccAlexander/Chameleon.git', :branch => 'wip/swift4'
  
end
