project 'tentenbox.xcodeproj'
platform :ios, '10.0'

target 'tentenbox' do
  use_frameworks!
  
  # code rules
  # https://github.com/realm/SwiftLint
  pod 'SwiftLint'

  # resources
  # https://github.com/mac-cain13/R.swift
  pod 'R.swift'

  # icons
  # https://github.com/PrideChung/FontAwesomeKit
  pod 'FontAwesomeKit/FontAwesome'
  
end
