project 'tentenbox.xcodeproj'
platform :ios, '10.0'

target 'tentenbox' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'SwiftLint'
  
end
